"""add stripe payment id

Revision ID: 082256ee8fb9
Revises: cca386f27207
Create Date: 2026-04-27 20:31:10.368602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '082256ee8fb9'
down_revision: Union[str, Sequence[str], None] = 'cca386f27207'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('stripe_payment_inten_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'stripe_payment_inten_id')
    # ### end Alembic commands ###
